### ISSUE TITLE
bug or something else

### ISSUE THREAD

**Issue by AnotherCrab1** [wijes/TerminalDesktop#11]
Hello i got problem with terminaldesktop.bundle here is error [Error  : Unity Log] Unable to open archive file: D:/Games/Lethal Company 10.12.23/Lethal Company/BepInEx/plugins/wijes-TerminalDesktop/terminaldesktop.bundle
[Error  : Unity Log] Failed to read data for the AssetBundle 'terminaldesktop.bundle'.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TerminalDesktopMod.Main.LoadFlashItem (UnityEngine.AssetBundle assetBundle) (at <2c2afc9011ce489395b60493ae230da6>:0)
TerminalDesktopMod.Main.Awake () (at <2c2afc9011ce489395b60493ae230da6>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable() i cant do anything with that is here solution?(im using thunderstore.io)

**Comment by AnotherCrab1** [comment]
someone help me please

**Comment by wijes** [comment]
Try this file
[terminaldesktop.zip](https://github.com/wijes/TerminalDesktop/files/14071274/terminaldesktop.zip)

**Comment by AnotherCrab1** [comment]
> Try this file [terminaldesktop.zip](https://github.com/wijes/TerminalDesktop/files/14071274/terminaldesktop.zip)

still doesnt work

**Comment by AnotherCrab1** [comment]
maybe there is something wrong with my game?

**Comment by wijes** [comment]
if you used manual download, then the mod folder should be called "wijes-TerminalDesktop-0.6.2", remove the version from the name so that it becomes "wijes-TerminalDesktop"

**Comment by AnotherCrab1** [comment]
> if you used manual download, then the mod folder should be called "wijes-TerminalDesktop-0.6.2", remove the version from the name so that it becomes "wijes-TerminalDesktop"

Still doesnt work

**Comment by AnotherCrab1** [comment]
> > if you used manual download, then the mod folder should be called "wijes-TerminalDesktop-0.6.2", remove the version from the name so that it becomes "wijes-TerminalDesktop"
> 
> Still doesnt work

btw there is no folder just 2 files

**Comment by wijes** [comment]
The downloaded archive should contain 6 files

**Comment by AnotherCrab1** [comment]
> The downloaded archive should contain 6 files

UHHHH

**Comment by AnotherCrab1** [comment]
there is archive that i downloaded
[Uploading wijes-TerminalDesktop-0.6.2 (1).zip…]()

**Comment by AnotherCrab1** [comment]
![Uploading 2024-01-27_14-17-18.png…]()

**Comment by AnotherCrab1** [comment]
![2024-01-27_14-17-18](https://github.com/wijes/TerminalDesktop/assets/157810589/f1a85dd7-c236-40f2-b8b0-7bcd020cb381)

**Comment by wijes** [comment]
Better start over
1) delete all mod files you have
2) go to https://thunderstore.io/c/lethal-company/p/wijes/TerminalDesktop/ and download manually
3) unzip the downloaded file into the "wijes-TerminalDesktop" folder
4) you should have 6 files in this folder
5) move this folder to your plugins folder

**Comment by AnotherCrab1** [comment]
> Better start over
> 
> 1. delete all mod files you have
> 2. go to https://thunderstore.io/c/lethal-company/p/wijes/TerminalDesktop/ and download manually
> 3. unzip the downloaded file into the "wijes-TerminalDesktop" folder
> 4. you should have 6 files in this folder
> 5. move this folder to your plugins folder

ITS STILL DOESNT WORK I DELETED EVERY  btw i accidentaly removed bepinx

**Comment by AnotherCrab1** [comment]
> > Better start over
> > 
> > 1. delete all mod files you have
> > 2. go to https://thunderstore.io/c/lethal-company/p/wijes/TerminalDesktop/ and download manually
> > 3. unzip the downloaded file into the "wijes-TerminalDesktop" folder
> > 4. you should have 6 files in this folder
> > 5. move this folder to your plugins folder
> 
> ITS STILL DOESNT WORK I DELETED EVERY btw i accidentaly removed bepinx

nvm i got bepinx back BUT ITS STILL DOESNT WORK

**Comment by AnotherCrab1** [comment]
> 3\. wijes-TerminalDesktop

wait wait IT WORKED TYSM YOU ARE BEST MOD CREATOR EVER
