### ISSUE TITLE
VIRUS

### ISSUE THREAD

**Issue by AnotherCrab1** [wijes/TerminalDesktop#13]
hello so there is problem with viruses in this mod like i was pooping and 1000 viruses would pop up so can you add config file so i can disable some things

**Comment by AnotherCrab1** [comment]
> hello so there is problem with viruses in this mod like i was pooping and 1000 viruses would pop up so can you add config file so i can disable some things

![Uploading 2024-01-27_19-57-34.png…]()

**Comment by AnotherCrab1** [comment]
![Uploading 2024-01-27_19-58-40.png…]()

**Comment by AnotherCrab1** [comment]
hello?

**Comment by wijes** [comment]
I don’t really understand the essence of the problem, but there are plans to add a configuration file
