### ISSUE TITLE
Camera isn't locked to the terminal, window bugs out+ possible Advancedcompany compat?

### ISSUE THREAD

**Issue by YnwLNE** [wijes/TerminalDesktop#2]
Currently (tested with other mods and without other mods) the camera statically to the terminal, causing the navigation of the desktop to be really tedious.

Also, I wonder if you could include compat for a mod called Advanced Company, a mod that adds a perk menu and extend deadline option. Would be nice for desktop shortcuts to those two

As for the window bugging out, this happens and again it happens regardless of other mods or not + pressing w while trying to type in terminal jolts the character forward.
![image](https://github.com/wijes/TerminalDesktop/assets/81484850/4468827c-dfa9-4ee7-8889-22d90bfdb70f)

**Comment by wijes** [comment]
1. Static on the terminal means that when the camera rotates, it is attracted to the center or does not react at all? When using the desktop, the camera should be free to rotate ~180 degrees horizontally and ~45 degrees vertically 
2. At the moment I have no plans to add functionality for other mods until I complete my
3. The window should be able to be scrolled if it doesn't fit, if I understood your problem correctly
![TerminalStore](https://github.com/wijes/TerminalDesktop/assets/81588539/f3783dd6-6131-4d0b-83fc-f5a52f4dfcad)

**Comment by YnwLNE** [comment]
> 1. Static on the terminal means that when the camera rotates, it is attracted to the center or does not react at all? When using the desktop, the camera should be free to rotate ~180 degrees horizontally and ~45 degrees vertically
> 2. At the moment I have no plans to add functionality for other mods until I complete my
> 3. The window should be able to be scrolled if it doesn't fit, if I understood your problem correctly
>    ![TerminalStore](https://private-user-images.githubusercontent.com/81588539/295793683-f3783dd6-6131-4d0b-83fc-f5a52f4dfcad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjYyNTQsIm5iZiI6MTcwNDk2NTk1NCwicGF0aCI6Ii84MTU4ODUzOS8yOTU3OTM2ODMtZjM3ODNkZDYtNjEzMS00ZDBiLTgzZmMtZjVhNTJmNGRmY2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA5MzkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YzQ1OGEzZWFiOTVkYzgwY2E3YWNlYWFmZTk1NzE3NjQ0NGY2NmNjNGFkZTMxZDFhMzhkMDQ2ODM5MzNmOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OparHHYoVVU5SpPdZ_X5e-RvtdGjL2AXH7IfR6yGyzQ)

Hello, by static camera I mean it not being to move at all and only focuses on the desktop. I wasn't aware it was a design feature but I feel like it would be a helpful option in the config to make it static because it does cause some light motion sickness(?) when using it for a while since you're having to follow the cursor. 

It's fine for no mod compat at the very release of this mod, I was just suggesting something in the future as I can see this mod being really expansive with desktop icons for various mods (suitterminal, perks, missions, etc).

As for the window, it seems there is an error where the background of the terminal interface will be replaced with an empty blue void like shown in the screenshot or a static image of your lower torso. Neither of these stop until you reset the lobby and it seems to happen more in online lobbies.

P.S, Idk if this is noted but randomly the terminal will turn to "Climb 'E'" instead of use/interact

**Comment by wijes** [comment]
Making the choice to have the camera static or not is a good idea, I think.

The terminal background can indeed change when you are in the game, since the camera has been moved into the world and reacts a little to lighting, but it is strange that it somehow draws parts of your torso.

**Comment by YnwLNE** [comment]
> Making the choice to have the camera static or not is a good idea, I think.
> 
> The terminal background can indeed change when you are in the game, since the camera has been moved into the world and reacts a little to lighting, but it is strange that it somehow draws parts of your torso.

maybe not completely static but locked in a little, just my idea though. It feels unnatural and slippery to navigate atm

**Comment by slovinsqui** [comment]
yeah, about the free camera when using the terminal, it is a nice change being able to look around in the ship for many reasons, but binding this feature to an input might be the best option, maybe holding right click or somehing

**Comment by bokkbokk** [comment]
> yeah, about the free camera when using the terminal, it is a nice change being able to look around in the ship for many reasons, but binding this feature to an input might be the best option, maybe holding right click or somehing

I think this is a wonderful idea, it's a bit nauseating moving the mouse around

**Comment by wijes** [comment]
Static camera added in version 0.6.1
