### ISSUE TITLE
Potential Shader Bug

### ISSUE THREAD

**Issue by Elfrrik** [wijes/TerminalDesktop#4]
When landing on weathered moons (flooded, rainy etc), the windows for the terminal are either blinding (image) or lightly shaded. I have tried with a fresh install with only terminaldesktop and dependencies, and found the same result.
![Lethal Company Screenshot 2024 01 11 - 19 25 56 35](https://github.com/wijes/TerminalDesktop/assets/80040305/a0932e48-3700-48b7-adad-f5a2e6abf03a)

**Comment by wijes** [comment]
Try the new version 0.5.5, the bug should be fixed
