### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by ChooMcoo** [wijes/TerminalDesktop#6]
Would you be willing to join the Lethal Company Modding discord and post your mod in the mod-releases forum? I just came across your mod and love the concept, and it would be a lot easier to follow your progress there and get a lot more feedback from people! If you're interested here's a link, otherwise no sweat, I'll still be checking it out and following along as best I can :)
https://discord.gg/lcmod

**Comment by wijes** [comment]
Thanks for the offer, but I don’t have much time or desire to design the topic somewhere else
