### ISSUE TITLE
Huge FPS drops when landed

### ISSUE THREAD

**Issue by BrawleyGithub** [wijes/TerminalDesktop#9]
This last update seems to have drastically worsened performance when the ship is landed. In a testing modpack with only this mod my FPS was near rock bottom on Experimentation. I did see a few red lines in the log at the start of the round:

[Error  : Unity Log] Setting width of already created render texture is not supported!
[Error  : Unity Log] Setting height of already created render texture is not supported!
[Error  : Unity Log] Trying to add Caret (TMPro.TMP_SelectionCaret) for graphic rebuild while we are already inside a graphic rebuild loop. This is not supported.

But I'm not sure this is the actual cause of the lag because it only happened once and the FPS only drops when on the moon.
I really like the desktop though, the camera change alone would have made this update perfect if not for the bizarre lag.

**Comment by wijes** [comment]
The bug was fixed in version 0.6.2
